### ISSUE TITLE
Error in binary cargo projects

### ISSUE THREAD

**Issue by skeuomorf** [flycheck/flycheck-rust#17] opened 2015-12-03 20:45 UTC
Opening the `utils` module in the following directory tree -Cargo binary project made with `cargo new hello --bin-. NOTE: The checker works fine inside the `main` module.
.
├── Cargo.lock
├── Cargo.toml
├── src
│   ├── main.rs
│   └── utils.rs
└── target
    └── debug
        ├── build
        ├── deps
        ├── examples
        ├── hello
        └── native
This error appears
"Suspicious state from syntax checker rust-cargo: Checker rust-cargo returned non-zero exit code 101, but no errors from output: no library targets found"

**Comment by mkpankov** [comment] 2015-12-04 09:09
Dupe of https://github.com/flycheck/flycheck-rust/issues/16

**Comment by lunaryorn** [comment] 2015-12-04 13:31
Indeed, that's a duplicate of #16, closing.

**Closed by lunaryorn** 2015-12-04 13:31 UTC
Labels: duplicate
