### ISSUE TITLE
No library targest found error in rust-cargo

### ISSUE THREAD

**Issue by Nuk9** [flycheck/flycheck-rust#16] opened 2015-11-14 01:49 UTC
Hello,
Now I have two rust files: main.rs and event.rs, where main.rs uses mod event.
When I run rust-cargo checker on main.rs it is using:

    cargo rustc -- -Z no-trans -L/Users/nuk/git/stitch_v2/target/debug -L/Users/nuk/git/stitch_v2/target/debug/deps

However when I run rust-cargo checker on event.rs:

    cargo rustc --lib -- -Z no-trans --test -L/Users/nuk/git/stitch_v2/target/debug -L/Users/nuk/git/stitch_v2/target/debug/deps
    no library targets found

Seems the reason is because my event.rs does not conain a "src/bin/" path as prefix.
Is there any reason why a mod in binary package must have a "src/bin/" as prefix?

**Comment by Nuk9** [comment] 2015-11-14 02:07
Another question is:
Cargo allows me to have two targes in one project, see [here](http://stackoverflow.com/questions/26946646/rust-package-with-both-a-library-and-a-binary).

Suppose we have both main.rs and lib.rs in same directory, at this time I run `C-c ! C-c rust-cargo` in main.rs it will return:

    cargo rustc -- -Z no-trans -L/Users/nuk/git/stitch_v2/target/debug -L/Users/nuk/git/stitch_v2/target/debug/deps
    extra arguments to `rustc` can only be passed to one target, consider filtering
    the package by passing e.g. `--lib` or `--bin NAME` to specify a single target

    Compilation exited abnormally with code 101 at Fri Nov 13 21:08:12

**Comment by lunaryorn** [comment] 2015-11-14 10:12
@Nuk9 Apparently Flycheck Rust does not detect that `event.rs` belongs to a binary.  I presume our detection logic is flawed, but I do not have the time to fix that.  My Rust knowledge is superficial, and its build model does not play well with Flycheck assumption that it can check individual files.

Likewise, Flycheck does not support packages with multiple targets.

Pull requests that improve Rust support are welcome (both here and in Flycheck itself), but I for my part am not going to spent any further time on adding more and more workarounds for Rusts.  Sorry.  Closing as wontfix.

**Closed by lunaryorn** 2015-11-14 10:12 UTC

**Comment by tomjakubowski** [comment] 2015-11-15 04:09
> Suppose we have both main.rs and lib.rs in same directory, at this time I run C-c ! C-c rust-cargo in main.rs it will return:

Seems to me the right thing to do is to have file-local variables to control what target `cargo rustc` will try to

**Comment by Hi-Angel** [comment] 2018-05-02 13:17
I don't get it, so how do I make flycheck to work with rust? E.g. I have a single `main.rs` — where should I add these `src/bin` paths OP mentioned?

**Comment by fmdkdd** [comment] 2018-05-03 08:08
@Hi-Angel The issue is rather old.  If you have setup `flycheck-rust` as per the README, it should take care of configuring `flycheck` for you by calling `cargo` in order to determine the build targets.

**Comment by Hi-Angel** [comment] 2018-05-03 08:13
@fmdkdd the part of README about setup is rather short, it's:

> * Setup Flycheck to follow the Cargo project layout

Without any references. I've no idea what would that mean.

To get the error I simply do:

1. `cargo new --bin foo`
2. Then open `foo/src/main.rs`, and use <kbd>M</kbd>-<kbd>x</kbd> <kbd>flycheck-mode</kbd>.

**Comment by fmdkdd** [comment] 2018-05-03 09:30
> Setup Flycheck to follow the Cargo project layout

That's the description of the project.  Below that, you can find installation instructions, namely (after installing `flycheck-rust` from MELPA):
```
(with-eval-after-load 'rust-mode
  (add-hook 'flycheck-mode-hook #'flycheck-rust-setup))
```
You can of course call `M-x flycheck-rust-setup` manually, but that would get tedious rather quickly.

**Comment by Hi-Angel** [comment] 2018-05-03 09:39
I see, thank you. Would that perhaps be better to move this part into the `#Usage` section? Also, the description of the project doesn't sound like description. I'd put there just `Flycheck support for Rust language`.
