### ISSUE TITLE
Errors not highlighted nor listed correctly

### ISSUE THREAD

**Issue by rgilton** [flycheck/flycheck-rust#73] opened 2019-01-02 13:32 UTC
Having loaded flycheck-rust from melpa (version '20180904.1117'), flycheck seems to be content with the rust/cargo arrangement (output of `flycheck-verify-setup` is all green for both `rust-cargo` and `rust`).  However when there are errors present in the rust file being edited, those errors are not highlighted, and they are not listed in the flycheck error buffer.

As an example, `C-c ! C-c RET` yields [this](https://gist.github.com/rgilton/d408bc4157fbdb967fe413aa5a386c65) output, but `C-c ! l` only lists one error at line 1 column 1, when in fact there are multiple errors/warnings and they are not in that position in the file.  Nothing is highlighted by flycheck in the buffer as an error.

I am using Emacs 26 and rust 1.31.0.

**Comment by rgilton** [comment] 2019-01-02 13:35
I've just noticed that what I have described above sounds very similar to that in  #71.

**Comment by fmdkdd** [comment] 2019-01-18 16:20
Yes, it does seem similar to #71.  Do you have a sample of code where you can reproduce the error that you can share?

**Comment by rgilton** [comment] 2019-01-24 11:33
The code that I was using was just the basic hello world code that you get from a `cargo new` invocation, and then just adding some lines that were obviously wrong to the code -- nothing particularly special, and I seemed to get the same error no matter what I did.

**Comment by fmdkdd** [comment] 2019-01-24 12:11
Then I'll close this issue in favor of #71 where we can keep gathering data.  I definitely cannot reproduce: a `cargo new` project checks fine for me.

**Closed by fmdkdd** 2019-01-24 12:11 UTC

**Comment by fmdkdd** [comment] 2019-02-01 10:10
@rgilton I see you have an outdated Flycheck from MELPA.  Can you update it and try again?

**Comment by rgilton** [comment] 2019-02-01 10:50
After updating flycheck to come from MELPA, everything is working.  Great!  Is there a way to get `flycheck-verify-setup` to check for this problem?

**Comment by rgilton** [comment] 2019-02-01 10:54
... and thanks!

**Comment by fmdkdd** [comment] 2019-02-01 13:32
@rgilton `flycheck-verify-setup` shows you the installed Flycheck version, but we could add a warning if you version is a few months older than the latest one, that's a good point.
